# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8a4e81831d7a0b9fb08ab4088a07aa36379eaf28eaf6ea647552433932443d632bf28beec8c7552cf8752e80b0f6f512c168c5e859591d2b4e79539bc13c8b2

test:
  secret_key_base: 589333e2e01ded03850745de395e07c2b4c9dda26a81af83018b328a914b7a3254651d52ae72da549ad441cd64761387f38635c672e56fa0d45261df15f00263

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
